ansible_connection: ssh
ansible_user: ec2-user
ansible_become: true
ansible_ssh_private_key_file: ~/.ssh/desktop.pem 

java_version: 1.8.0

elasticsearch:
    repo_version: '6.x'
    java_max_mem: '-Xms512m'
    java_min_mem: '-Xmx512m'
    node_name: 'My First Node'
    cluster_name: 'mycluster1'
    admin_user: 'admin'
    admin_password:  '123456'

