ansible_connection: ssh
ansible_user: ec2-user
ansible_become: true
ansible_ssh_private_key_file: ~/.ssh/desktop.pem 

java_version: 1.8.0

# es - elasticsearch
es:
  repo_version: '6.x'
  java_max_mem: '-Xms1g'
  java_min_mem: '-Xmx1g'
  node_name: 'My First Node'
  cluster_name: mycluster1
  network_host: "0.0.0.0"
  discovery_type: single-node
  credentials:
    xpack_security_enabled: 'true'
    auto_passwords_store: /etc/elasticsearch/default_auto_passwords
    admin_user: 'admin'
    admin_password:  '123456'
  encrypted_communication:
    xpack_security_transport_ssl_enabled: 'true'
    CA_path: '/etc/elasticsearch/myCA.p12'
    ##  For Empty password puted single quote
    CA_password: "''"
    keystore: '/etc/elasticsearch/my-Kyestore.p12'
    ##  For Empty password puted single quote
    keystore_password: "''"

