---
- name: Configuring EC2 instances for kafka
  hosts: localhost
  connection: local
#  remote_user: ubuntu
#  become: true
#  become_method: sudo
  gather_facts: no
  vars:
      - REGION: us-east-1
      - ec2_tag_key: Role
      - ec2_tag_value: kafka
      # - ec2_tag_zookeerp_value: zookeeper
# --------------------------------------
##  JAVA
# --------------------------------------
      - java_home: /usr/local/java/jdk
      #- jdk_archive_url: http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz
      #- jdk_archive_filename: jdk-8u171-linux-x64.tar.gz
      - jdk_archive_url: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
      - jdk_archive_filename: jdk-8u181-linux-x64.tar.gz
      - jdk_version: jdk1.8.0_181
      #- jdk_version: jdk1.8.0_171

# --------------------------------------
## Common -  Common Location information.
# --------------------------------------
#common:
      - install_base_path: /usr/local
      - soft_link_base_path: /opt

# --------------------------------------
## Zookeeper
# --------------------------------------
#zookeeper:
      - java_home: /usr/local/java/jdk
      - version: 3.5.7
      - port: 2181
      - user: zkadmin
      - group: zkadmin
      - password: $6$SDOmVPRk$Jcb/qm2QTKsLABvBHx/CYtsgmShobAr7BwhWWbrrQIHfjndIzcbJhv1b2Dh2Rv.KgWhjTipT3MJUBQFf1g5O70
      - data_store: /mnt/data/zookeeper
      - logging: /mnt/data/zookeeper_logging
      - url: https://www.apache.org/dist/zookeeper/zookeeper-{{ version }}
      - zookeeper_file_name: apache-zookeeper-{{ version }}
      - log4j_properties_url: https://raw.githubusercontent.com/amitganvir23/amazon-cloud-formation-kakfa/master/zookeeper-templates/log4j.properties

  roles:
        - zookeeper