- name: Elasticsearch Provisioning
  hosts: {{ elasticsearch_ec2_tag }}
  remote_user: ec2-user
  become: true
  become_method: sudo
  gather_facts: no
  tasks:
  - import_role:
      name: elasticsearch