---
- name: Kafka Broker Provisioning
  hosts: localhost
  #remote_user: ec2-user
  #become: true
  #become_method: sudo
  gather_facts: no
  vars:
      kafka_broker_group: "{{ groups['tag_Role_kafka_broker'] }}"
      zookeeper_group: "{{ groups['tag_Role_zookeeper'] }}"
      schema_registry_group: "{{ groups['tag_Role_schema_registry'] }}"
      kafka_connect_group: "{{ groups['tag_Role_kafka_connect'] }}"
      ksql_group: "{{ groups['tag_Role_ksql'] }}"
      kafka_rest_group: "{{ groups['tag_Role_kafka_rest'] }}"
      control_center_group: "{{ groups['tag_Role_control_center'] }}"
  tasks:
  - name: making kafka dynamic inventory
    template:
      src: "{{ playbook_dir }}//hosts/kafka_inventory.j2"
      dest: "{{ playbook_dir }}/hosts/kafka_inventory"
