- name: Elasticsearch Provisioning
  hosts: elasticsearch_master, elasticsearch_node
  remote_user: ec2-user
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
  - import_role:
      name: elasticsearch

# - name: Elasticsearch Provisioning
#   hosts: elasticsearch_master
#   remote_user: ec2-user
#   become: true
#   become_method: sudo
#   gather_facts: no
#   tasks:
#   - import_role:
#       name: elasticsearch-master

# - name: Elasticsearch Provisioning
#   hosts: elasticsearch_node
#   remote_user: ec2-user
#   become: true
#   become_method: sudo
#   gather_facts: no
#   tasks:
#   - import_role:
#       name: elasticsearch-node
