elasticsearch_master:
  hosts:
    ### Master 1 - IP/Hostname
    54.210.151.132:
      node_name: Master01
      node_master: 'true'
    54.196.102.245:
      node_name: Master02
      node_master: 'true'

elasticsearch_node:
  hosts:
    ### Node1 - IP/Hostname
    54.198.205.41:
      node_name: Node01
      node_master: 'false'
