elasticsearch_master:
  hosts:
    ### Master 1 - IP/Hostname
    127.0.0.1:
      node_name: Master01
      node_master: 'true'
    127.0.0.2:
      node_name: Master02
      node_master: 'true'

elasticsearch_node:
  hosts:
    ### Node1 - IP/Hostname
    127.0.0.3:
      node_name: Node01
      node_master: 'false'
    127.0.0.4:
      node_name: Node02
      node_master: 'false'

