---
# tasks file for roles/elasticsearch
- name: Removing java 7 version
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: installing Java
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-{{ java_version }}-openjdk
    - java-{{  java_version }}-openjdk-devel

- name: Creating java paramter
  copy:
    dest: /etc/profile.d/java.sh
    content: |
      export JAVA_HOME=/usr/lib/jvm/jre-openjdk
      export PATH=$PATH:$JAVA_HOME/bin
      export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar

- name: Importing RPM GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Creating elasticsearch repo
  copy:
    dest: /etc/yum.repos.d/elasticsearch.repo
    content: |
      [elasticsearch-{{ es.repo_version }}]
      name=Elasticsearch repository for {{ es.repo_version }} packages
      baseurl=https://artifacts.elastic.co/packages/{{ es.repo_version }}/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md

- name: installing elasticsearch
  yum:
    name: elasticsearch
    state: present

##=====================================  elasticsearch encrypted communication =====================================
- name: Creating a elasticsearch encrypted communication
  block:
    - name: Checking CA file
      stat: 
        path: "{{ es.encrypted_communication.CA_path }}" 
      register: file_result_ca
      
    - name: Creating a CA file
      shell: "/usr/share/elasticsearch/bin/elasticsearch-certutil ca --out {{ es.encrypted_communication.CA_path }} --pass {{ es.encrypted_communication.CA_password }} -s"
      when: file_result_ca.stat.isdir is not defined

    - name: Checking keypair file 
      stat: 
        path: "{{ es.encrypted_communication.keystore }}"
      register: file_result_key

    - name: Creating a key
      shell: "/usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca {{ es.encrypted_communication.CA_path }} --out {{ es.encrypted_communication.keystore }} --ca-pass {{ es.encrypted_communication.CA_password }} --pass {{ es.encrypted_communication.keystore_password }} -s"
      when: file_result_key.stat.isdir is not defined
  when: es.encrypted_communication.xpack_security_transport_ssl_enabled|upper == "TRUE"

#================================ configuration ===========================
- name: Updating java memory
  lineinfile:
    path: "/etc/elasticsearch/jvm.options"
    line: "{{ item.line }}"
    regexp: '^{{ item.regexp }}'
  with_items:
    - { regexp: '-Xms1g', line: '{{ es.java_max_mem }}' }
    - { regexp: '-Xmx1g', line: '{{ es.java_min_mem }}' }

- name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
  blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    block: |
      node.name: {{ es.node_name}}
      cluster.name: {{ es.cluster_name}}
      network.host: {{ es.network_host}}
      discovery.type: {{ es.discovery_type}}
      xpack.security.enabled: {{ es.credentials.xpack_security_enabled }}
      {% if es.encrypted_communication.xpack_security_transport_ssl_enabled|upper == "TRUE" %}
      xpack.security.transport.ssl.enabled: {{ es.encrypted_communication.xpack_security_transport_ssl_enabled}}
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.keystore.path: {{ es.encrypted_communication.keystore }}
      xpack.security.transport.ssl.truststore.path: {{ es.encrypted_communication.CA_path }}
      {% endif %}

- name: Updating ES configuration
  file:
    path: /etc/elasticsearch
    recurse: yes
    owner: elasticsearch
    group: elasticsearch

- name: Start and Enabled elasticsearch Service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Validating port number
  wait_for:
    host: localhost
    port: 9200
    timeout: 60

# - name: Validating elasticsearch vai URL
#   uri:
#     url: "http://127.0.0.1:9200"
#     method: GET
#     status_code: 200
#   register: result
#   until: result.status == 200
#   retries: 3
#   delay: 2


##===================================== xpack credentials =====================================

- name: Applying X-Pack and creating credentials
  block:
    - name: Checking default password file is present
      stat: 
        path: /etc/elasticsearch/default_passwords
      register: file_result
      
    - name: Creating a default password for elasticsearch
      shell: "echo y | /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto > /etc/elasticsearch/default_passwords"
      when: file_result.stat.isdir is not defined

    - name: Verifying a user
      shell: "/usr/share/elasticsearch/bin/elasticsearch-users list {{ es.credentials.admin_user }}"
      ignore_errors: yes
      register: user_result

    - name: Creating a user
      shell: "/usr/share/elasticsearch/bin/elasticsearch-users useradd {{ es.credentials.admin_user }} -p {{ es.credentials.admin_password }} -r superuser"
      when: '"ERROR" in user_result.stdout'

    - name: Validating elasticsearch vai URL
      uri:
        url: "http://127.0.0.1:9200"
        method: GET
        status_code: '200'
        user: '{{ es.credentials.admin_user }}'
        password: '{{ es.credentials.admin_password }}'
      register: result
      until: result.status == 200
      retries: 3
      delay: 2
  when: es.credentials.xpack_security_enabled|upper == "TRUE"


