---
# tasks file for roles/elasticsearch
- debug:
    msg: "Hello"

- name: installing Java 8
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: Creating java paramter
  copy:
    dest: /etc/profile.d/java8.sh
    content: |
      export JAVA_HOME=/usr/lib/jvm/jre-openjdk
      export PATH=$PATH:$JAVA_HOME/bin
      export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar

- name: Importing RPM GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Creating elasticsearch repo
  copy:
    dest: /etc/yum.repos.d/elasticsearch.repo
    content: |
      [elasticsearch-6.x]
      name=Elasticsearch repository for 6.x packages
      baseurl=https://artifacts.elastic.co/packages/6.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md

- name: installing elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Updating java memory
  lineinfile:
    path: "/etc/elasticsearch/jvm.options"
    line: "{{ item.line }}"
    regexp: '^{{ item.regexp }}'
  with_items:
    - { regexp: '-Xms1g', line: '-Xms512m' }
    - { regexp: '-Xmx1g', line: '-Xmx512m' }

- name: add lines
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: '{{ item }}'
  with_items:
    - 'node.name: "My First Node"'
    - 'cluster.name: mycluster1'
    - 'network.host: 0.0.0.0'
    - 'discovery.type: single-node'
    - 'xpack.security.enabled: true'

- name: Start and Enabled elasticsearch Service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Validating port number
  wait_for:
    host: localhost
    port: 9200
    timeout: 60

# - name: Validating elasticsearch vai URL
#   uri:
#     url: "http://127.0.0.1:9200"
#     method: GET
#     status_code: 200
#   register: result
#   until: result.status == 200
#   retries: 3
#   delay: 2

- stat: path=/etc/elasticsearch/default_passwords
  register: file_result

- name: Creating default password for elasticsearch
  shell: "echo y|/usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto > /etc/elasticsearch/default_passwords"
  when: file_result.stat.isdir is not defined

- name: Verifying a user
  shell: "/usr/share/elasticsearch/bin/elasticsearch-users list amit"
  ignore_errors: yes
  register: user_result

- name: Creating a user
  shell: "/usr/share/elasticsearch/bin/elasticsearch-users useradd amit -p 123456 -r superuser"
  when: '"ERROR" in user_result'

- name: Validating elasticsearch vai URL
  uri:
    url: "http://127.0.0.1:9200"
    method: GET
    status_code: 200
    user: amit
    password: 123456
  register: result
  until: result.status == 200
  retries: 3
  delay: 2

